# -*- mode: ruby -*-
# vi: set ft=ruby :

N = 3


Vagrant.configure("2") do |config|

#  config.ssh.forward_agent = true
  config.vm.define "m-k8s" do |cfg|
	cfg.vm.box = "rshash/Ubuntu_20.04-M1-Mac"
    cfg.vm.hostname = "m-k8s"
    cfg.vm.network "private_network", ip: "192.168.1.10"
	cfg.vm.network "forwarded_port",guest: 22, host: 60010, auto_currect: true, id: "ssh"
    cfg.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
	  vb.customize ["modifyvm", :id, "--groups", "/k8s-SgMST-1.13.1(github_SysNet4Admin)"]
    end
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
    SHELL
   cfg.vm.provision "shell", path: "install.sh"
   cfg.vm.provision "shell", path: "config.sh"
   cfg.vm.provision "shell", path: "master.sh"

  end


  (1..N).each do |i|
    config.ssh.forward_agent = true
    config.vm.define "w#{i}-k8s" do |cfg|
      cfg.vm.box = "rshash/Ubuntu_20.04-M1-Mac"
      cfg.vm.hostname = "w#{i}-k8s"
      cfg.vm.network "private_network", ip: "192.168.1.10#{i}"
      cfg.vm.network "forwarded_port",guest: 22, host: "6010#{i}", auto_currect: true, id: "ssh"
      cfg.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--groups", "/k8s-SgMST-1.13.1(github_SysNet4Admin)"]
      end
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get upgrade -y
      SHELL

      cfg.vm.provision "shell", path: "install.sh"
      cfg.vm.provision "shell", path: "config.sh"
      cfg.vm.provision "shell", path: "worker.sh"

    end
  end

end
