# -*- mode: ruby -*-
# vi: set ft=ruby :

N = 2


Vagrant.configure("2") do |config|

#  config.ssh.forward_agent = true
  config.vm.define "master" do |cfg|
	cfg.vm.box = "rshash/Ubuntu_20.04-M1-Mac"
    cfg.vm.hostname = "master"
    cfg.vm.network "public_network", ip: "192.168.0.100"
	cfg.vm.network "forwarded_port",guest: 22, host: 60010, auto_currect: true, id: "ssh"
    cfg.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = "2"
      vb.memory = "3072"
	  vb.customize ["modifyvm", :id, "--groups", "/k8s-SgMST-1.13.1(github_SysNet4Admin)"]
    end
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y

    SHELL

  end


  (1..N).each do |i|
#    config.ssh.forward_agent = true
    config.vm.define "worker#{i}" do |cfg|
	  cfg.vm.box = "rshash/Ubuntu_20.04-M1-Mac"	
      cfg.vm.hostname = "worker#{i}"
      cfg.vm.network "public_network", ip: "192.168.0.10#{i}"
	  cfg.vm.network "forwarded_port",guest: 22, host: "6010#{i}", auto_currect: true, id: "ssh"
      cfg.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = "1"
        vb.memory = "2048"
		vb.customize ["modifyvm", :id, "--groups", "/k8s-SgMST-1.13.1(github_SysNet4Admin)"]
      end
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get upgrade -y
	
      SHELL

    end
  end

end
