# -*- mode: ruby -*-
# vi: set ft=ruby :

N = 2


Vagrant.configure("2") do |config|

#  config.ssh.forward_agent = true
  config.vm.define "m-k8s" do |cfg|
	cfg.vm.box = "rshash/Ubuntu_20.04-M1-Mac"
    cfg.vm.hostname = "m-k8s"
    cfg.vm.network "private_network", ip: "192.168.1.10"
	  cfg.vm.network "forwarded_port",guest: 22, host: 60010, auto_currect: true, id: "ssh"
    cfg.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "4"
    end
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
    SHELL
   cfg.vm.provision "shell", path: "install.sh"
   cfg.vm.provision "shell", path: "config.sh"
   cfg.vm.provision "shell", path: "master.sh"

  end


  (1..N).each do |i|
    config.ssh.forward_agent = true
    config.vm.define "w#{i}-k8s" do |cfg|
      cfg.vm.box = "rshash/Ubuntu_20.04-M1-Mac"
      cfg.vm.hostname = "w#{i}-k8s"
      cfg.vm.network "private_network", ip: "192.168.1.10#{i}"
      cfg.vm.network "forwarded_port",guest: 22, host: "6010#{i}", auto_currect: true, id: "ssh"
      cfg.vm.provider "vmware_desktop" do |vb|
        vb.vmx["memsize"] = "1024"
        vb.vmx["numvcpus"] = "2"
      end
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get upgrade -y
      SHELL

      cfg.vm.provision "shell", path: "install.sh"
      cfg.vm.provision "shell", path: "config.sh"
      cfg.vm.provision "shell", path: "worker.sh"

    end
  end

end
